puts "Deleting old data 👴"
Van.destroy_all



Van.create(year_make_model: "1980 VW Vanagon Westfalia", description: " Original air-cooled camper van! Beautiful Assuan paint with a fully functioning kitchen.", transmission: " Manual", roof: " Pop-Top", equipment:" Surfboard, Giant bag on roof filled with frisbees, awning, board games, camp chairs", dogs: "Yes!", location: "Los Angeles Area", owner: "Lars Nueffer", price: "200", image: "https://s1.cdn.autoevolution.com/images/news/cute-1980-volkswagen-vanagon-westfalia-is-everything-you-need-sells-with-no-reserve-184313_1.jpg")
Van.create(year_make_model: "1986 VW Syncro Westfalia", description: " Modifed 4WD Syncro Westfalia. Has propane powered auxilarry heater and solar panels", transmission: " Manual", roof: "Pop-Top", equipment:" Dining set, ARB awning, recovery gear, camp table, camp chairs, blankets", dogs: "Yes!", location: "Bay Area", owner: "Stella Wong", price: "300", image: "https://bringatrailer.com/wp-content/uploads/2020/11/1986_volkswagen_vanagon_syncro_westfalia_1615998531d363e2fe1986_volkswagen_vanagon_syncro_westfalia_161512280565ef66e7dff9f9876d7be9bc5-9383-42f5-9d10-0361e7c6203e-004PkK.jpg?fit=940%2C626")
Van.create(year_make_model: "1967 VW T1 Westfalia", description: " Vintage picnic basket and Cocacola with real cociane included! You'll have a hoppin' time in this time capsule!", transmission: " Manual", roof: " Pop-Top", equipment:" twister game, toy ray guns, dining set, camp chairs, cigars for the whole family", dogs: "no", location: "Bay Area", owner: "Richie McGeezaks", price: "500", image: "https://silodrome.com/wp-content/uploads/2021/05/Volkswagen-Type-2-Westfalia-Camper.jpg")
Van.create(year_make_model: "1991 VW Syncro Westfalia", description: " I did it! I'm the guy that painted their late moded Westy 'Pastel', everyone will think your rental is old, and junky, but they'll be wrong! ", transmission: " Manual", roof: " Pop-Top", equipment:" Big loud stereo, stand up paddle boards, one wheel unicycle, xbox pro, vr glasses", dogs: "no", location: "Bay Area", owner: "Carlton Campell", price: "300", image: "https://bringatrailer.com/wp-content/uploads/2018/05/1526071337f8f0f5558af70779aFullSizeRender-22.jpg")
Van.create(year_make_model: "1968 VW T2 Westfalia", description: " Hopefully this beautiful bay window bus will get you to your destination... Very slow, very beautiful.", transmission: " Manual", roof: " Pop-Top", equipment:" Kitchen set, axe, tables, chairs, games", dogs: "No", location: "Bay Area", owner: "Alex Cameron", price: "200", image: "https://images.squarespace-cdn.com/content/v1/5b6332193917ee6b4a4afc47/1589929279424-7AX6DZQL0ALP2G9XS3LE/Boos-2.jpg")
Van.create(year_make_model: "1974 VW T2 Westfalia", description: " All redone interior in white and blue. Please don't get it dirty.", transmission: " Manual", roof: " Pop-Top", equipment:" Champange bucket, acoustic guitar, white and blue leather interior... perfect for camping!", dogs: "No", location: "Fresno", owner: "Kev Keverson", price: "200", image: "https://bringatrailer.com/wp-content/uploads/2022/05/1974_volkswagen_bus_pxl_20220531_134333166-48915.jpg?fit=940%2C627")
Van.create(year_make_model: "1985 VW Vanagon Westfalia", description: " Starwars themed van with Electronic compressor fridge, sink and stove.", transmission: " Manual", roof: "High-Top", equipment:" catan board, nintendo swtich, awning, cornhole set, camp chairs", dogs: "yes", location: "Sacramento Area", owner: "Adrian Solo", price: "250", image: "https://i0.wp.com/www.curbsideclassic.com/wp-content/uploads/2020/05/20200527_162509.jpg")
Van.create(year_make_model: "1987 VW Syncro Doka", description: " You could rent a normal camper... or you could rent my truck that I TURNED into a camper! ", transmission: " Manual", roof: " Custom truck bed camper", equipment:" Aero bed, tent for outside, gasoline genorator, campchairs, camp tables", dogs: "Yes", location: "Sacramento Area", owner: "Trucker Camerson", price: "300", image: "https://expeditionportal.com/media/2022/07/22E9C8E4-5CEA-41DB-90BC-C37DC8D297F4-scaled.jpg")


puts "seeding🌱complete"
